# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

default_language_version:
  python: python3.9

default_stages: [commit, push]
exclude: './data'

fail_fast: false

repos:
  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
        name: black
        language: python
        entry: black
        args: [ --config=api/pyproject.toml, --diff, api/]
        types: [ python ]

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
      - id: flake8
        name: flake8
        language: python
        entry: bash -c "cd api && flake8"
        types: [ python ]


  - repo: https://github.com/timothycrosley/isort
    rev: 5.7.0
    hooks:
      - id: isort
        additional_dependencies: [ toml ]

  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v0.910
  #   hooks:
  #     - id: mypy
  #       entry: mypy
  #       language: python
  #       'types': [ python ]
  #       args: [ "--ignore-missing-imports", "--scripts-are-modules", "--install-types", "--non-interactive"]
  #       require_serial: true

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: check-merge-conflict
      - id: check-added-large-files
      - id: debug-statements
      - id: detect-private-key
